first of all we import the libraries
Library	Purpose
pandas     >>>	Data read aur analysis
numpy      >>>  Numerical operations
matplotlib >>>	Visualization
seaborn	   >>>  Statistical visualization

In [18]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import the raw data for further processing

In [19]:
file_path="../data/Adidas US Sales Datasets.xlsx"
df =pd.read_excel(file_path)

seeing the random 5 rows in the all data set

In [20]:
df.sample(5)

,Retailer,Retailer ID,Invoice Date,Region,State,City,Product,Price per Unit,Units Sold,Total Sales,Operating Profit,Operating Margin,Sales Method
4846,Sports Direct,1197831,4/5/21,South,Tennessee,Knoxville,Women's Street Footwear,$19.00,180,"$3,420","$1,847",54%,Online
8219,West Gear,1128299,1/17/20,West,Nevada,Las Vegas,Women's Athletic Footwear,$41.00,93,"$3,813","$1,563",41%,Outlet
2165,Kohl's,1128299,3/25/21,West,New Mexico,Albuquerque,Women's Street Footwear,$55.00,400,"$220,000","$77,000",35%,Online
456,Foot Locker,1185732,11/19/21,Northeast,Pennsylvania,Philadelphia,Men's Apparel,$65.00,125,"$81,250","$24,375",30%,Outlet
8599,West Gear,1185732,7/10/21,West,Utah,Salt Lake City,Men's Apparel,$28.00,140,"$3,920","$1,490",38%,Outlet

checking the all data information

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9648 entries, 0 to 9647
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Retailer          9648 non-null   object
 1   Retailer ID       9648 non-null   int64
 2   Invoice Date      9648 non-null   object
 3   Region            9648 non-null   object
 4   State             9648 non-null   object
 5   City              9648 non-null   object
 6   Product           9648 non-null   object
 7   Price per Unit    9648 non-null   object
 8   Units Sold        9648 non-null   object
 9   Total Sales       9648 non-null   object
 10  Operating Profit  9648 non-null   object
 11  Operating Margin  9648 non-null   object
 12  Sales Method      9648 non-null   object
dtypes: int64(1), object(12)
memory usage: 980.0+ KB

numerical data summary

In [22]:
df.describe()

        Retailer ID
count  9.648000e+03
mean   1.173850e+06
std    2.636038e+04
min    1.128299e+06
25%    1.185732e+06
50%    1.185732e+06
75%    1.185732e+06
max    1.197831e+06

missing values analysis

calculate the percentage missing values

In [23]:
missing_percentage = (df.isnull().sum()/ len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_report[
    missing_report["Missing_Values"] > 0].sort_values(by="Missing_Percentage",ascending=False)

Empty DataFrame
Columns: [Missing_Values, Missing_Percentage]
Index: []

duplicate values ko analysis by order ID

In [24]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.columns.tolist()

['Retailer',
 'Retailer ID',
 'Invoice Date',
 'Region',
 'State',
 'City',
 'Product',
 'Price per Unit',
 'Units Sold',
 'Total Sales',
 'Operating Profit',
 'Operating Margin',
 'Sales Method']

unique values analyse

In [26]:
categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].nunique())
    print(df[col].unique()[:20])

Retailer
6
['Foot Locker' 'Walmart' 'Sports Direct' 'West Gear' "Kohl's" 'Amazon']

Invoice Date
724
['1/1/20' '1/2/20' '1/3/20' '1/4/20' '1/5/20' '1/6/20' '1/7/20' '1/8/20'
 '1/21/20' '1/22/20' '1/23/20' '1/24/20' '1/25/20' '1/26/20' '1/27/20'
 '1/28/20' '1/29/20' '1/30/20' '1/31/20' '2/1/20']

Region
5
['Northeast' 'South' 'West' 'Midwest' 'Southeast']

State
50
['New York' 'Texas' 'California' 'Illinois' 'Pennsylvania' 'Nevada'
 'Colorado' 'Washington' 'Florida' 'Minnesota' 'Montana' 'Tennessee'
 'Nebraska' 'Alabama' 'Maine' 'Alaska' 'Hawaii' 'Wyoming' 'Virginia'
 'Michigan']

City
52
['New York' 'Houston' 'San Francisco' 'Los Angeles' 'Chicago' 'Dallas'
 'Philadelphia' 'Las Vegas' 'Denver' 'Seattle' 'Miami' 'Minneapolis'
 'Billings' 'Knoxville' 'Omaha' 'Birmingham' 'Portland' 'Anchorage'
 'Honolulu' 'Orlando']

Product
6
["Men's Street Footwear" "Men's Athletic Footwear"
 "Women's Street Footwear" "Women's Athletic Footwear" "Men's Apparel"
 "Women's Apparel"]

Price per Unit
94
['$50.00 ' '$40.00 ' '$45.00 ' '$60.00 ' '$55.00 ' '$65.00 ' '$70.00 '
 '$25.00 ' '$35.00 ' '$30.00 ' '$80.00 ' '$75.00 ' '$20.00 ' '$85.00 '
 '$100.00 ' '$90.00 ' '$95.00 ' '$15.00 ' '$10.00 ' '$110.00 ']

Units Sold
361
['1,200' '1,000' '850' '900' '1,250' '950' '825' '1,220' '925' '800' '875'
 '1,050' '1,275' '1,025' '1,100' '1,075' '1,150' '975' '920' '700']

Total Sales
3138
['$600,000 ' '$500,000 ' '$400,000 ' '$382,500 ' '$540,000 ' '$625,000 '
 '$450,000 ' '$380,000 ' '$371,250 ' '$610,000 ' '$462,500 ' '$360,000 '
 '$510,000 ' '$475,000 ' '$495,000 ' '$732,000 ' '$508,750 ' '$425,000 '
 '$525,000 ' '$650,000 ']

Operating Profit
4224
['$300,000 ' '$150,000 ' '$140,000 ' '$133,875 ' '$162,000 ' '$125,000 '
 '$312,500 ' '$135,000 ' '$133,000 ' '$129,937 ' '$305,000 ' '$138,750 '
 '$126,000 ' '$153,000 ' '$118,750 ' '$148,500 ' '$366,000 ' '$152,625 '
 '$157,500 ' '$148,750 ']

Operating Margin
66
['50%' '30%' '35%' '25%' '45%' '20%' '15%' '40%' '55%' '10%' '60%' '65%'
 '61%' '42%' '46%' '37%' '62%' '44%' '47%' '49%']

Sales Method
3
['In-store' 'Outlet' 'Online']

identifying the numerical data values

and for categorical data values

first data quality report analysis

In [27]:
data_quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str),
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100),
    "Unique_Values": df.nunique()
})

data_quality_report

,Column,Data_Type,Missing_Values,Missing_Percentage,Unique_Values
Retailer,Retailer,object,0,0.0,6
Retailer ID,Retailer ID,int64,0,0.0,4
Invoice Date,Invoice Date,object,0,0.0,724
Region,Region,object,0,0.0,5
State,State,object,0,0.0,50
City,City,object,0,0.0,52
Product,Product,object,0,0.0,6
Price per Unit,Price per Unit,object,0,0.0,94
Units Sold,Units Sold,object,0,0.0,361
Total Sales,Total Sales,object,0,0.0,3138
Operating Profit,Operating Profit,object,0,0.0,4224
Operating Margin,Operating Margin,object,0,0.0,66
Sales Method,Sales Method,object,0,0.0,3