first of all we import the libraries
Library	Purpose
pandas     >>>	Data read aur analysis
numpy      >>>  Numerical operations
matplotlib >>>	Visualization
seaborn	   >>>  Statistical visualization

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import the raw data for further processing

In [2]:
file_path="../data/raw/Adidas_Synthetic_Messy_Data_Analytics_Project.xlsx"
df =pd.read_excel(
    file_path,
    sheet_name="Messy_Raw_Data")

seeing the random 5 rows in the all data set

In [3]:
df.sample(5)

,Order_ID,Order_Date,Customer_ID,Country,Region,City,Category,Product,Gender,Size,...,Cost_USD,Profit_USD,Customer_Rating,Returned,Order_Status,Customer_Age,Shipping_Days,Inventory_Available,Marketing_Spend_USD,Customer_Lifetime_Value_USD
1703,ORD-101703,1970-01-01 05:00:45.173,CUST-10417,Germany,Europe,Munich,Lifestyle,Campus,Male,XL,...,93.70,-16.42,4.0,No,Completed,45.0,3.0,437,3791.92,1274.11
1391,ORD-101391,1970-01-01 05:00:45.505,CUST-10890,USA,North America,Chicago,Lifestyle,Gazelle,Male,NaN,...,110.49,43.79,4.0,No,Completed,43.0,2.0,952,97173.22,1078.22
399,ORD-100399,1970-01-01 05:00:45.968,CUST-10401,Pakistan,South Asia,Rawalpindi,Running,Solarboost,Male,44,...,99.43,82.06,4.0,No,Completed,31.0,2.0,891,34319.25,2708.41
155,ORD-100155,1970-01-01 05:00:45.409,CUST-10609,USA,North America,Houston,Lifestyle,Campus,Male,42,...,58.20,51.76,4.0,No,Completed,23.0,4.0,765,NaN,3832.59
2085,ORD-102085,1970-01-01 05:00:45.235,CUST-10051,Australia,Oceania,Brisbane,Football,Predator,Female,43,...,63.46,-17.90,5.0,No,Completed,34.0,5.0,435,3633.56,3313.08

checking the all data information

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3045 entries, 0 to 3044
Data columns (total 28 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Order_ID                     3045 non-null   object
 1   Order_Date                   3045 non-null   datetime64[ns]
 2   Customer_ID                  3045 non-null   object
 3   Country                      3045 non-null   object
 4   Region                       3045 non-null   object
 5   City                         2802 non-null   object
 6   Category                     3045 non-null   object
 7   Product                      3045 non-null   object
 8   Gender                       2863 non-null   object
 9   Size                         2832 non-null   object
 10  Sales_Channel                3045 non-null   object
 11  Customer_Segment             3045 non-null   object
 12  Payment_Method               3045 non-null   object
 13  Campaign                     2322 non-null   object
 14  Quantity                     3045 non-null   int64
 15  Unit_Price_USD               3045 non-null   float64
 16  Discount_Rate                2891 non-null   float64
 17  Revenue_USD                  3045 non-null   float64
 18  Cost_USD                     3045 non-null   float64
 19  Profit_USD                   3045 non-null   float64
 20  Customer_Rating              2742 non-null   float64
 21  Returned                     3045 non-null   object
 22  Order_Status                 3045 non-null   object
 23  Customer_Age                 2892 non-null   float64
 24  Shipping_Days                2834 non-null   float64
 25  Inventory_Available          3045 non-null   int64
 26  Marketing_Spend_USD          2862 non-null   float64
 27  Customer_Lifetime_Value_USD  3045 non-null   float64
dtypes: datetime64[ns](1), float64(10), int64(2), object(15)
memory usage: 666.2+ KB

numerical data summary

In [5]:
df.describe()

,Order_Date,Quantity,Unit_Price_USD,Discount_Rate,Revenue_USD,Cost_USD,Profit_USD,Customer_Rating,Customer_Age,Shipping_Days,Inventory_Available,Marketing_Spend_USD,Customer_Lifetime_Value_USD
count,3045,3045.000000,3045.000000,2891.000000,3045.000000,3045.000000,3045.000000,2742.000000,2892.000000,2834.000000,3045.000000,2862.000000,3045.000000
mean,1970-01-01 05:00:45.465020689,1.981938,124.886470,0.119993,1456.138309,92.000814,53.532883,3.975930,41.770055,4.056457,487.633826,50162.253319,2516.829957
min,1970-01-01 05:00:44.927000,-1.000000,40.120000,-0.200000,-1000.000000,16.440000,-55.160000,1.000000,5.000000,-2.000000,0.000000,509.310000,100.510000
25%,1970-01-01 05:00:45.183000,1.000000,89.100000,0.000000,87.340000,54.850000,27.140000,3.000000,30.000000,2.000000,232.000000,24848.325000,1297.020000
50%,1970-01-01 05:00:45.465000,1.000000,121.340000,0.100000,121.510000,76.760000,44.420000,4.000000,42.000000,3.000000,486.000000,50025.025000,2522.910000
75%,1970-01-01 05:00:45.744000,2.000000,153.750000,0.150000,171.270000,108.300000,67.790000,5.000000,54.000000,5.000000,734.000000,75407.277500,3723.620000
max,1970-01-01 05:00:46.022000,150.000000,249.630000,3.000000,500000.000000,621.510000,462.200000,5.000000,150.000000,90.000000,999.000000,99995.720000,4998.390000
std,NaN,9.287601,45.553191,0.184938,25591.805662,59.878643,42.129666,1.033268,14.909830,3.730081,289.617498,28665.208683,1409.470648

missing values analysis

In [6]:
missing_values = df.isnull().sum()
missing_values[missing_values > 0].sort_values(ascending=False)

Campaign               723
Customer_Rating        303
City                   243
Size                   213
Shipping_Days          211
Marketing_Spend_USD    183
Gender                 182
Discount_Rate          154
Customer_Age           153
dtype: int64

calculate the percentage missing values

In [7]:
missing_percentage = (df.isnull().sum()/ len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_report[
    missing_report["Missing_Values"] > 0].sort_values(by="Missing_Percentage",ascending=False)

                     Missing_Values  Missing_Percentage
Campaign                        723           23.743842
Customer_Rating                 303            9.950739
City                            243            7.980296
Size                            213            6.995074
Shipping_Days                   211            6.929392
Marketing_Spend_USD             183            6.009852
Gender                          182            5.977011
Discount_Rate                   154            5.057471
Customer_Age                    153            5.024631

duplicate values ko analysis by order ID

In [8]:
df.duplicated().sum()

np.int64(45)

In [9]:
df["Order_ID"].duplicated().sum()

np.int64(45)

In [10]:
df[df["Order_ID"].duplicated(keep=False)].sort_values("Order_ID")

,Order_ID,Order_Date,Customer_ID,Country,Region,City,Category,Product,Gender,Size,...,Cost_USD,Profit_USD,Customer_Rating,Returned,Order_Status,Customer_Age,Shipping_Days,Inventory_Available,Marketing_Spend_USD,Customer_Lifetime_Value_USD
44,ORD-100044,1970-01-01 05:00:45.543,CUST-10373,USA,North America,Houston,Outdoor,Ridgewalker,Unisex,XS,...,79.63,108.05,3.0,No,Completed,33.0,5.0,524,84353.93,2756.74
3020,ORD-100044,1970-01-01 05:00:45.543,CUST-10373,USA,North America,Houston,Outdoor,Ridgewalker,Unisex,XS,...,79.63,108.05,3.0,No,Completed,33.0,5.0,524,84353.93,2756.74
3011,ORD-100052,1970-01-01 05:00:45.400,CUST-10089,India,South Asia,Chennai,Football,X Crazyfast,Unisex,M,...,65.61,50.65,4.0,No,Completed,31.0,3.0,600,44413.75,2072.45
52,ORD-100052,1970-01-01 05:00:45.400,CUST-10089,India,South Asia,Chennai,Football,X Crazyfast,Unisex,M,...,65.61,50.65,4.0,No,Completed,31.0,3.0,600,44413.75,2072.45
3041,ORD-100063,1970-01-01 05:00:45.068,CUST-10048,USA,North America,NaN,Outdoor,Agravic,Male,43,...,55.72,25.75,4.0,No,Completed,24.0,3.0,143,24852.87,854.35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3014,ORD-102776,1970-01-01 05:00:45.381,CUST-10860,UAE,Middle East,Sharjah,Running,Duramo,Male,43,...,37.41,23.37,4.0,No,Completed,47.0,5.0,901,46375.19,2794.21
2851,ORD-102851,1970-01-01 05:00:45.565,CUST-10512,UAE,Middle East,NaN,Outdoor,Ridgewalker,Male,42,...,116.72,70.31,5.0,No,Completed,57.0,5.0,950,17268.80,2368.46
3033,ORD-102851,1970-01-01 05:00:45.565,CUST-10512,UAE,Middle East,NaN,Outdoor,Ridgewalker,Male,42,...,116.72,70.31,5.0,No,Completed,57.0,5.0,950,17268.80,2368.46
3025,ORD-102895,1970-01-01 05:00:46.013,CUST-10537,India,South Asia,Bangalore,Running,Adizero,Female,44,...,131.57,48.48,5.0,No,Completed,53.0,2.0,660,37469.95,350.85
2895,ORD-102895,1970-01-01 05:00:46.013,CUST-10537,India,South Asia,Bangalore,Running,Adizero,Female,44,...,131.57,48.48,5.0,No,Completed,53.0,2.0,660,37469.95,350.85

In [11]:
df.columns.tolist()

['Order_ID',
 'Order_Date',
 'Customer_ID',
 'Country',
 'Region',
 'City',
 'Category',
 'Product',
 'Gender',
 'Size',
 'Sales_Channel',
 'Customer_Segment',
 'Payment_Method',
 'Campaign',
 'Quantity',
 'Unit_Price_USD',
 'Discount_Rate',
 'Revenue_USD',
 'Cost_USD',
 'Profit_USD',
 'Customer_Rating',
 'Returned',
 'Order_Status',
 'Customer_Age',
 'Shipping_Days',
 'Inventory_Available',
 'Marketing_Spend_USD',
 'Customer_Lifetime_Value_USD']

unique values analyse

In [12]:
categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    print(f"\n{col}")
    print(df[col].nunique())
    print(df[col].unique()[:20])

Order_ID
3000
['ORD-100000' 'ORD-100001' 'ORD-100002' 'ORD-100003' 'ORD-100004'
 'ORD-100005' 'ORD-100006' 'ORD-100007' 'ORD-100008' 'ORD-100009'
 'ORD-100010' 'ORD-100011' 'ORD-100012' 'ORD-100013' 'ORD-100014'
 'ORD-100015' 'ORD-100016' 'ORD-100017' 'ORD-100018' 'ORD-100019']

Customer_ID
862
['CUST-10769' 'CUST-10189' 'CUST-10897' 'CUST-10401' 'CUST-10216'
 'CUST-10230' 'CUST-10642' 'CUST-10484' 'CUST-10339' 'CUST-10317'
 'CUST-10612' 'CUST-10183' 'CUST-10402' 'CUST-10610' 'CUST-10130'
 'CUST-10895' 'CUST-10459' 'CUST-10658' 'CUST-10115' 'CUST-10489']

Country
13
['India' 'Pakistan' 'Saudi Arabia' 'Germany' 'Australia' 'USA' 'UAE' 'UK'
 'SAUDI ARABIA' 'INDIA' 'GERMANY' 'PAKISTAN' 'AUSTRALIA']

Region
5
['South Asia' 'Middle East' 'Europe' 'Oceania' 'North America']

City
29
['Mumbai' 'Karachi' 'Riyadh' 'Berlin' 'Sydney' 'Delhi' nan 'Jeddah'
 'Melbourne' 'Los Angeles' 'Sharjah' 'Birmingham' 'Dammam' 'Abu Dhabi'
 'Lahore' 'Chennai' 'Faisalabad' 'Rawalpindi' 'London' 'Dubai']

Category
12
['Running' 'Training' 'Lifestyle' 'Football' 'Outdoor' 'Basketball'
 ' Training ' ' Outdoor ' ' Basketball ' ' Lifestyle ' ' Football '
 ' Running ']

Product
24
['Solarboost' 'Ultraboost' 'Everyday' 'Samba' 'Adizero' 'Copa' 'F50'
 'Rapidmove' 'Superstar' 'Ridgewalker' 'Dropset' 'Dame' 'Gazelle' 'Terrex'
 'X Crazyfast' 'Duramo' 'Powerlift' 'Own The Game' 'Campus' 'Five Ten']

Gender
3
['Male' 'Unisex' nan 'Female']

Size
9
['S' 'XS' '43' '42' 'XL' '45' 'L' nan '44' 'M']

Sales_Channel
10
['Wholesale' 'wholesale' 'Marketplace' 'Mobile App' 'Online Store'
 'Retail Store' 'marketplace' 'mobile app' 'online store' 'retail store']

Customer_Segment
3
['Consumer' 'Premium Consumer' 'Business']

Payment_Method
5
['Bank Transfer' 'Debit Card' 'Credit Card' 'Digital Wallet'
 'Cash on Delivery']

Campaign
5
['Eid Campaign' 'Summer Sale' 'Sports Event' 'New Year Sale' nan
 'Black Friday']

Returned
2
['Yes' 'No']

Order_Status
4
['Returned' 'Completed' 'Pending' 'Cancelled']

identifying the numerical data values

In [13]:
numeric_columns = df.select_dtypes(include=np.number).columns.tolist()

numeric_columns

['Quantity',
 'Unit_Price_USD',
 'Discount_Rate',
 'Revenue_USD',
 'Cost_USD',
 'Profit_USD',
 'Customer_Rating',
 'Customer_Age',
 'Shipping_Days',
 'Inventory_Available',
 'Marketing_Spend_USD',
 'Customer_Lifetime_Value_USD']

and for categorical data values

In [14]:
categorical_columns = df.select_dtypes(include="object").columns.tolist()

categorical_columns

['Order_ID',
 'Customer_ID',
 'Country',
 'Region',
 'City',
 'Category',
 'Product',
 'Gender',
 'Size',
 'Sales_Channel',
 'Customer_Segment',
 'Payment_Method',
 'Campaign',
 'Returned',
 'Order_Status']

In [15]:
df["Order_Date"].dtype

dtype('<M8[ns]')

first data quality report analysis

In [16]:
data_quality_report = pd.DataFrame({
    "Column": df.columns,
    "Data_Type": df.dtypes.astype(str),
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": (df.isnull().sum() / len(df) * 100),
    "Unique_Values": df.nunique()
})

data_quality_report

,Column,Data_Type,Missing_Values,Missing_Percentage,Unique_Values
Order_ID,Order_ID,object,0,0.000000,3000
Order_Date,Order_Date,datetime64[ns],0,0.000000,1018
Customer_ID,Customer_ID,object,0,0.000000,862
Country,Country,object,0,0.000000,13
Region,Region,object,0,0.000000,5
City,City,object,243,7.980296,29
Category,Category,object,0,0.000000,12
Product,Product,object,0,0.000000,24
Gender,Gender,object,182,5.977011,3
Size,Size,object,213,6.995074,9
Sales_Channel,Sales_Channel,object,0,0.000000,10
Customer_Segment,Customer_Segment,object,0,0.000000,3
Payment_Method,Payment_Method,object,0,0.000000,5
Campaign,Campaign,object,723,23.743842,5
Quantity,Quantity,int64,0,0.000000,8
Unit_Price_USD,Unit_Price_USD,float64,0,0.000000,2741
Discount_Rate,Discount_Rate,float64,154,5.057471,10
Revenue_USD,Revenue_USD,float64,0,0.000000,2756
Cost_USD,Cost_USD,float64,0,0.000000,2675
Profit_USD,Profit_USD,float64,0,0.000000,2584
Customer_Rating,Customer_Rating,float64,303,9.950739,5
Returned,Returned,object,0,0.000000,2
Order_Status,Order_Status,object,0,0.000000,4
Customer_Age,Customer_Age,float64,153,5.024631,51
Shipping_Days,Shipping_Days,float64,211,6.929392,12
Inventory_Available,Inventory_Available,int64,0,0.000000,949
Marketing_Spend_USD,Marketing_Spend_USD,float64,183,6.009852,2819
Customer_Lifetime_Value_USD,Customer_Lifetime_Value_USD,float64,0,0.000000,2986