for cleaning process we import the python libraries

In [37]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import the data set

In [38]:
RAW_DATA_PATH="../data/Adidas US Sales Datasets.xlsx"
df = pd.read_excel(RAW_DATA_PATH)

copy the raw data for backup
deep=True kyun?
Yeh raw data ki independent copy banata hai.meand original data per koi effect nahi parta

In [39]:
df_raw = df.copy(deep=True)

confirm the duplicate rows

In [40]:
duplicate_count = df.duplicated().sum()
print(f"the duplicated rows are {duplicate_count}")

the duplicated rows are 0

remove the exact duplicated rows

In [41]:
rows_before = len(df)
print(f"rows_before length with duplicate rows {rows_before}")
df = df.drop_duplicates(keep="first").reset_index(drop=True)
rows_after = len(df)
print(f"rows after the  length without duplicate rows {rows_after}")

rows_before length with duplicate rows 9648
rows after the  length without duplicate rows 9648

In [42]:
df.shape

(9648, 13)

column renaming

In [43]:
df.columns = (
    df.columns
      .str.strip()
      .str.lower()
      .str.replace(" ", "_")
)

 removeing empty columns

In [44]:
df.drop(columns=["unnamed:_0"], inplace=True, errors="ignore")

In [45]:
missing_percentage = (df.isnull().sum()/ len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_report[
    missing_report["Missing_Values"] > 0].sort_values(by="Missing_Percentage",ascending=False)

Empty DataFrame
Columns: [Missing_Values, Missing_Percentage]
Index: []

In [46]:
df.to_excel(
    "../data/Adidas_Cleaned_Data.xlsx",
    index=False
)

In [47]:
clean_data=pd.read_excel("../data/Adidas_Cleaned_Data.xlsx")
clean_data.sample(5)

,retailer,retailer_id,invoice_date,region,state,city,product,price_per_unit,units_sold,total_sales,operating_profit,operating_margin,sales_method
96,Walmart,1197831,8/16/20,South,Texas,Houston,Men's Apparel,$45.00,600,"$270,000","$81,000",30%,Outlet
6699,Kohl's,1197831,3/12/21,Midwest,Kansas,Wichita,Men's Street Footwear,$20.00,153,"$3,060","$1,499",49%,Online
1972,West Gear,1128299,7/16/21,South,Louisiana,New Orleans,Men's Athletic Footwear,$95.00,750,"$712,500","$285,000",40%,Online
879,Kohl's,1189833,1/16/21,Midwest,Montana,Billings,Men's Athletic Footwear,$45.00,375,"$168,750","$50,625",30%,Outlet
9060,Foot Locker,1128299,12/12/21,Southeast,Georgia,Atlanta,Women's Athletic Footwear,$40.00,143,"$5,720","$2,460",43%,Outlet