for cleaning process we import the python libraries

In [1381]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import the data set

In [1382]:
RAW_DATA_PATH="../data/raw/Adidas_Synthetic_Messy_Data_Analytics_Project.xlsx"
df = pd.read_excel(
    RAW_DATA_PATH,
    sheet_name="Messy_Raw_Data"
)

copy the raw data for backup
deep=True kyun?
Yeh raw data ki independent copy banata hai.meand original data per koi effect nahi parta

In [1383]:
df_raw = df.copy(deep=True)

confirm the duplicate rows

In [1384]:
duplicate_count = df.duplicated().sum()
print(f"the duplicated rows are {duplicate_count}")

the duplicated rows are 45

remove the exact duplicated rows

In [1385]:
rows_before = len(df)
print(f"rows_before length with duplicate rows {rows_before}")
df = df.drop_duplicates(keep="first").reset_index(drop=True)
rows_after = len(df)
print(f"rows after the  length without duplicate rows {rows_after}")

rows_before length with duplicate rows 3045
rows after the  length without duplicate rows 3000

In [1386]:
df.shape

(3000, 28)

text whitespacing removeing

In [1387]:
text_columns = df.select_dtypes(
    include=["object", "string"]
).columns.tolist()
for col in text_columns:
    df[col] = df[col].str.strip()

country and sale channel standardization

In [1388]:
df["Country"]=(df["Country"].str.strip().str.title())
df['Sales_Channel']=(df['Sales_Channel'].str.strip().str.title())

invalid valuesin the numerical data type 
steps 
  1 >> range select
  2 >> convert it into the nan
  3 >> fill by  different methods like means ,median ,mode ,knn etc

In [1389]:
df.loc[
    (df["Customer_Age"] < 13) |
    (df["Customer_Age"] > 100),
    "Customer_Age"
] = np.nan

df.loc[
    df["Shipping_Days"] < 0,
    "Shipping_Days"
] = np.nan

df.loc[
    (df["Discount_Rate"] < 0) |
    (df["Discount_Rate"] > 1),
    "Discount_Rate"
] = np.nan

In [1390]:
from sklearn.impute import KNNImputer
knn = KNNImputer(n_neighbors=5, weights="distance")

In [1391]:
knn_features = ["Customer_Age","Customer_Rating","Shipping_Days",
                "Discount_Rate","Marketing_Spend_USD","Quantity",
                "Unit_Price_USD","Revenue_USD","Cost_USD","Profit_USD"]
df[knn_features] = knn.fit_transform(
    df[knn_features])

In [1392]:
df[
    [
        "Customer_Age",
        "Customer_Rating",
        "Shipping_Days",
        "Discount_Rate",
        "Marketing_Spend_USD"
    ]
].describe()

,Customer_Age,Customer_Rating,Shipping_Days,Discount_Rate,Marketing_Spend_USD
count,3000.000000,3000.000000,3000.000000,3000.000000,3000.000000
mean,41.561839,3.977904,4.042461,0.111262,50010.771989
std,13.185137,0.990751,3.615718,0.100545,28005.982080
min,18.000000,1.000000,0.000000,0.000000,509.310000
25%,31.000000,3.615570,2.949828,0.050000,26100.510522
50%,41.978835,4.000000,3.278493,0.100000,50011.409400
75%,53.000000,5.000000,5.000000,0.150000,74004.775000
max,64.000000,5.000000,90.000000,0.500000,99995.720000

In [1393]:
missing_percentage = (df.isnull().sum()/ len(df)) * 100

missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": missing_percentage
})

missing_report[
    missing_report["Missing_Values"] > 0].sort_values(by="Missing_Percentage",ascending=False)

          Missing_Values  Missing_Percentage
Campaign             714                23.8
City                 240                 8.0
Size                 210                 7.0
Gender               180                 6.0

changing the data type of custumer age,custumer rating ,shiping days

In [1394]:
df['Customer_Rating'].unique()

array([5.        , 3.        , 4.        , 2.        , 3.11200179,
       4.77376737, 4.36141925, 3.85905668, 3.68992611, 3.98998058,
       1.        , 4.44928141, 4.05299944, 4.07433708, 3.53567358,
       3.99096324, 3.58967968, 4.05623289, 4.26927087, 4.08341556,
       4.6188944 , 4.41356833, 2.99811144, 4.23769182, 3.68999966,
       3.7988798 , 4.49902812, 3.6439808 , 3.34200965, 3.69404636,
       4.03560742, 3.06340618, 4.35504937, 3.87165024, 4.08044736,
       4.28840256, 4.40372669, 3.83993292, 4.47096089, 3.19239749,
       4.57474384, 4.59202348, 3.72041777, 3.9520629 , 3.76615946,
       3.2307636 , 3.88060952, 4.05389009, 4.13396928, 4.1000506 ,
       3.91472407, 3.73298491, 2.88119239, 4.26111293, 3.98320425,
       4.30085217, 3.8150506 , 4.11654735, 4.17443516, 4.2387681 ,
       4.02054985, 4.51151268, 3.19952254, 3.73828107, 4.64864639,
       4.19949316, 3.45765191, 3.80770528, 3.40568933, 3.99855577,
       3.58471234, 3.69841188, 3.90928012, 4.18404386, 3.53464281,
       4.01896056, 4.5907769 , 3.86849745, 4.16423959, 3.98967646,
       3.38732227, 3.00350114, 4.18132955, 4.75793762, 3.86145789,
       4.324159  , 3.38821704, 4.4268381 , 4.33151986, 3.5206881 ,
       4.14425205, 3.19925975, 3.32728428, 4.23210077, 3.79307733,
       3.64228703, 3.4070365 , 4.14111677, 3.12137016, 3.43409925,
       2.96041547, 4.3264637 , 4.18160285, 3.33449554, 4.56067619,
       3.64327309, 2.90836605, 3.48310576, 4.257451  , 4.2232685 ,
       3.63197942, 3.66940687, 4.33230477, 4.04303323, 4.17101426,
       4.31325523, 3.56478391, 4.64680588, 4.44945552, 3.3477126 ,
       3.68556347, 4.31887668, 3.43692944, 3.10687671, 3.85337183,
       4.91517287, 3.18130116, 4.11102811, 4.01011415, 3.71400973,
       4.6625978 , 3.67706743, 4.17932709, 4.24785666, 4.64368593,
       4.35839817, 4.41737289, 4.65441808, 4.51607199, 4.31332028,
       3.22647727, 4.24254561, 4.34003907, 4.84766771, 3.99423426,
       4.25053581, 3.96894929, 3.71915042, 4.19426997, 3.77394391,
       3.03652527, 3.72267072, 4.18622295, 3.824821  , 4.20433096,
       4.1819065 , 3.22824371, 4.4239858 , 4.14863462, 3.76630613,
       4.35823033, 3.4899651 , 3.94604214, 4.09031024, 4.15622124,
       4.27381363, 3.99695338, 4.15275817, 4.57184746, 4.1942901 ,
       4.21799031, 4.42812483, 4.03478153, 3.18415749, 4.20818568,
       4.1503578 , 3.26448761, 3.9458817 , 3.53214569, 4.7279867 ,
       4.97810446, 4.16175798, 3.61715862, 3.90019092, 3.8240249 ,
       4.14755918, 3.60244815, 3.83891601, 3.79950659, 3.82058828,
       4.47419144, 4.04326862, 4.43694358, 4.81710634, 3.83175783,
       3.4757086 , 3.31801321, 4.37090881, 3.59380282, 3.61080421,
       4.31359936, 4.3721863 , 3.42085352, 4.0224941 , 3.94336981,
       4.1754495 , 4.03130122, 3.8530826 , 4.00063396, 4.44721163,
       3.22856562, 3.64145277, 3.55549359, 3.54213391, 4.80126421,
       3.98917105, 4.25600412, 4.14922641, 4.2799773 , 4.48818037,
       3.675914  , 4.55924227, 3.97708468, 4.63613437, 4.18435212,
       4.28334829, 3.9788462 , 4.56132465, 4.22512626, 4.82833682,
       4.25330801, 4.82355546, 4.23858886, 3.14726684, 4.36716313,
       3.90572127, 3.47534412, 4.05782287, 3.06627055, 3.35048915,
       4.29742693, 3.35666318, 4.0282356 , 3.26864392, 3.73610316,
       4.20325008, 3.89689874, 4.15702756, 3.6956453 , 4.24465256,
       3.30874118, 2.41621858, 4.22001404, 4.21846146, 4.4645591 ,
       4.59681619, 3.73940053, 3.25618728, 4.15003228, 4.2830256 ,
       4.5743756 , 3.88215947, 3.87522966, 2.63241121, 3.31606566,
       4.4269415 , 4.52853856, 4.08297633, 3.68191418, 4.4672285 ,
       4.26113165, 4.36369459, 4.40021541, 4.18706272, 3.83248904,
       4.24116494, 4.03794369, 3.80986322, 4.46044294, 3.75257739,
       3.76893526, 3.92018451, 4.02963594, 4.42952002, 4.62671525,
       4.39883682, 3.73873709, 3.70820833, 3.89975615, 4.16200952,
       3.98289402, 3.66275539, 2.58555553, 4.38972109, 4.6069416 ,
       4.5226106 , 4.48783658, 4.19106545, 4.34307699, 3.38281612,
       4.05079817, 4.43724895])

changing the customer age,customer rating,shipping days  columns ki data type changes

In [1395]:
df['Customer_Age']=df['Customer_Age'].astype(int)
df['Customer_Rating']=df['Customer_Rating'].astype(int)
df['Shipping_Days']=df['Shipping_Days'].astype(int)

In [1396]:
df['Customer_Age'].unique()

array([40, 64, 37, 43, 62, 58, 18, 47, 54, 34, 24, 63, 39, 21, 38, 19, 57,
       42, 33, 45, 29, 28, 46, 36, 56, 53, 25, 20, 30, 55, 23, 48, 31, 59,
       22, 32, 44, 51, 41, 26, 49, 61, 52, 35, 27, 60, 50])

In [1397]:
df['Discount_Rate'].unique()

array([0.2       , 0.05      , 0.        , 0.15      , 0.3       ,
       0.12591379, 0.1       , 0.5       , 0.03910769, 0.22433474,
       0.06881769, 0.11082096, 0.0582202 , 0.06278006, 0.07316601,
       0.08153544, 0.06060182, 0.0647134 , 0.0932597 , 0.0700722 ,
       0.06910081, 0.08676056, 0.11561709, 0.15      , 0.12758311,
       0.11466267, 0.1124561 , 0.09540278, 0.01716837, 0.18012852,
       0.04175135, 0.07315043, 0.11783694, 0.0180721 , 0.14918718,
       0.15404937, 0.07419826, 0.14977258, 0.0995158 , 0.07113023,
       0.06020728, 0.07222529, 0.14770747, 0.06319169, 0.14632533,
       0.06791825, 0.11987732, 0.11228155, 0.08405565, 0.03265157,
       0.04412094, 0.11810434, 0.12729222, 0.07011096, 0.09134382,
       0.06284552, 0.11707546, 0.06614858, 0.07178847, 0.12091178,
       0.28829829, 0.13541523, 0.1173182 , 0.15939545, 0.04313827,
       0.1019582 , 0.05875725, 0.12345205, 0.06662503, 0.01876099,
       0.10443371, 0.15875952, 0.12963239, 0.05666747, 0.11073476,
       0.15056002, 0.15973127, 0.08642562, 0.04304235, 0.23099005,
       0.17359058, 0.04066411, 0.0851067 , 0.13431147, 0.08687313,
       0.10940785, 0.18965539, 0.13199043, 0.09107912, 0.11831142,
       0.16844714, 0.13704842, 0.01144012, 0.09997274, 0.05889099,
       0.03552891, 0.15044724, 0.14912078, 0.10298931, 0.09747894,
       0.13244549, 0.06619588, 0.06607467, 0.12490138, 0.12636618,
       0.07916218, 0.3174375 , 0.11558562, 0.1350528 , 0.13870334,
       0.14308074, 0.14960147, 0.06989816, 0.09951937, 0.10789733,
       0.09369602, 0.08017301, 0.09682183, 0.07454385, 0.10163092,
       0.15858742, 0.08036726, 0.04805865, 0.12329323, 0.10679509,
       0.07367592, 0.2937847 , 0.07356172, 0.06551645, 0.13768524,
       0.12029204, 0.07355277, 0.02272057, 0.07663543, 0.11083541,
       0.06990197, 0.09185408, 0.09885054, 0.14345128, 0.07798016,
       0.1481455 , 0.1236717 , 0.048027  , 0.03980414, 0.09473216,
       0.15739244, 0.09054789, 0.0836906 , 0.09575109, 0.03777796,
       0.02957188, 0.03408082, 0.21133614, 0.12047365, 0.06677133,
       0.1470459 , 0.16701582, 0.05063823, 0.12676067, 0.07494031,
       0.11063689, 0.03753168, 0.05903831, 0.15360708, 0.1315863 ,
       0.11209667, 0.06813242, 0.14836331, 0.10993336, 0.22078185,
       0.12310914, 0.06807178, 0.08272844, 0.09946901, 0.07245061,
       0.00927283])

In [1398]:
df['Discount_Rate'] = (df['Discount_Rate'] * 100).round(2)

In [1399]:
df['Discount_Rate'].unique()

array([20.  ,  5.  ,  0.  , 15.  , 30.  , 12.59, 10.  , 50.  ,  3.91,
       22.43,  6.88, 11.08,  5.82,  6.28,  7.32,  8.15,  6.06,  6.47,
        9.33,  7.01,  6.91,  8.68, 11.56, 12.76, 11.47, 11.25,  9.54,
        1.72, 18.01,  4.18, 11.78,  1.81, 14.92, 15.4 ,  7.42, 14.98,
        9.95,  7.11,  6.02,  7.22, 14.77,  6.32, 14.63,  6.79, 11.99,
       11.23,  8.41,  3.27,  4.41, 11.81, 12.73,  9.13, 11.71,  6.61,
        7.18, 12.09, 28.83, 13.54, 11.73, 15.94,  4.31, 10.2 ,  5.88,
       12.35,  6.66,  1.88, 10.44, 15.88, 12.96,  5.67, 11.07, 15.06,
       15.97,  8.64,  4.3 , 23.1 , 17.36,  4.07,  8.51, 13.43,  8.69,
       10.94, 18.97, 13.2 ,  9.11, 11.83, 16.84, 13.7 ,  1.14,  5.89,
        3.55, 15.04, 14.91, 10.3 ,  9.75, 13.24,  6.62, 12.49, 12.64,
        7.92, 31.74, 13.51, 13.87, 14.31, 14.96,  6.99, 10.79,  9.37,
        8.02,  9.68,  7.45, 10.16, 15.86,  8.04,  4.81, 12.33, 10.68,
        7.37, 29.38,  7.36,  6.55, 13.77, 12.03,  2.27,  7.66,  9.19,
        9.89, 14.35,  7.8 , 14.81, 12.37,  4.8 ,  3.98,  9.47, 15.74,
        9.05,  8.37,  9.58,  3.78,  2.96,  3.41, 21.13, 12.05,  6.68,
       14.7 , 16.7 ,  5.06, 12.68,  7.49, 11.06,  3.75,  5.9 , 15.36,
       13.16, 11.21,  6.81, 14.84, 10.99, 22.08, 12.31,  8.27,  7.25,
        0.93])

In [1400]:
df['Marketing_Spend_USD'].unique()
df['Marketing_Spend_USD'].dtypes

dtype('float64')

remaning missing values of categorical data handle

In [1401]:
remaining_missing = pd.DataFrame({
""
    "Missing_Count": df.isnull().sum(),

    "Missing_%":
    round(df.isnull().mean()*100,2)
})
remaining_missing = remaining_missing[
    remaining_missing["Missing_Count"]>0
]
remaining_missing

          Missing_Count  Missing_%
City                240        8.0
Gender              180        6.0
Size                210        7.0
Campaign            714       23.8

In [1402]:
invalid = ["?","Unknown","N/A","None"]
df["Gender"] = df["Gender"].replace(invalid, np.nan)

In [1403]:
df['Gender'].isna().sum()

np.int64(180)

In [1404]:
df["Gender"] = df["Gender"].fillna(df["Gender"].mode()[0])

In [1405]:
df['City'].unique()

array(['Mumbai', 'Karachi', 'Riyadh', 'Berlin', 'Sydney', 'Delhi', nan,
       'Jeddah', 'Melbourne', 'Los Angeles', 'Sharjah', 'Birmingham',
       'Dammam', 'Abu Dhabi', 'Lahore', 'Chennai', 'Faisalabad',
       'Rawalpindi', 'London', 'Dubai', 'Manchester', 'Houston',
       'Hamburg', 'Chicago', 'Kolkata', 'Munich', 'Bangalore', 'Brisbane',
       'New York', 'Islamabad'], dtype=object)

In [1406]:
df["City"] = (
    df.groupby("Country")["City"]
      .transform(lambda x: x.fillna(x.mode().iloc[0] if not x.mode().empty else np.nan))
)

In [1407]:
df['Size'].unique()

array(['S', 'XS', '43', '42', 'XL', '45', 'L', nan, '44', 'M'],
      dtype=object)

In [1408]:
size_mode = df["Size"].mode()[0]
df["Size"] = df["Size"].fillna(size_mode)

In [1409]:
df['Size'].unique()

array(['S', 'XS', '43', '42', 'XL', '45', 'L', '44', 'M'], dtype=object)

In [1410]:
size_map = {
    "XS": 36,
    "S": 38,
    "M": 40,
    "L": 42,
    "XL": 44
}
df["Size"] = df["Size"].replace(size_map)
df["Size"] = pd.to_numeric(df["Size"], errors="coerce")

In [1411]:
df["Campaign"].unique()

array(['Eid Campaign', 'Summer Sale', 'Sports Event', 'New Year Sale',
       nan, 'Black Friday'], dtype=object)

In [1412]:
df["Campaign"] = df["Campaign"].fillna("No Campaign")

In [1413]:
missing_percentage = (df.isnull().sum()/ len(df)) * 100
missing_report = pd.DataFrame({
    "Missing_Values": df.isnull().sum(),
    "Missing_Percentage": missing_percentage})
missing_report[
    missing_report["Missing_Values"] > 0].sort_values(by="Missing_Percentage",ascending=False)

Empty DataFrame
Columns: [Missing_Values, Missing_Percentage]
Index: []

In [1414]:
df['Revenue_USD'].unique()

array([170.09, 193.52, 134.59, ...,  59.77,  38.27, 308.18], shape=(2756,))

In [1415]:
df.to_csv(
    "../data/processed/Adidas_Cleaned_Data.csv",
    index=False
)

In [1416]:
clean_data=pd.read_csv("../data/processed/Adidas_Cleaned_Data.csv")
clean_data.sample(5)

,Order_ID,Order_Date,Customer_ID,Country,Region,City,Category,Product,Gender,Size,...,Cost_USD,Profit_USD,Customer_Rating,Returned,Order_Status,Customer_Age,Shipping_Days,Inventory_Available,Marketing_Spend_USD,Customer_Lifetime_Value_USD
1706,ORD-101706,1970-01-01 05:00:45.612,CUST-10072,India,South Asia,Delhi,Outdoor,Ridgewalker,Male,38,...,132.32,58.81,4,No,Completed,57,6,880,704.180000,4035.36
1895,ORD-101895,1970-01-01 05:00:45.944,CUST-10047,Uae,Middle East,Dubai,Football,Copa,Unisex,36,...,63.27,58.49,4,No,Cancelled,62,5,730,55529.700000,730.71
2700,ORD-102700,1970-01-01 05:00:45.937,CUST-10307,Usa,North America,Chicago,Outdoor,Terrex,Male,36,...,71.02,38.91,4,No,Pending,63,2,847,79050.470000,427.77
1435,ORD-101435,1970-01-01 05:00:45.079,CUST-10443,Uae,Middle East,Dubai,Running,Adizero,Female,38,...,63.56,33.69,4,No,Completed,56,3,534,62136.327994,2281.16
2654,ORD-102654,1970-01-01 05:00:45.721,CUST-10842,Uae,Middle East,Abu Dhabi,Basketball,Harden,Unisex,40,...,60.47,21.16,4,No,Completed,22,3,631,18126.490000,950.32